spring.application.name=demo

spring.datasource.url=${DB_DSURL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

supabase.url=${DB_URL}
supabase.service-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbnNhZ3JxcWxpYmN6Y2Fic25xIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTgzMDk3MSwiZXhwIjoyMTAxNDA2OTcxfQ.INsUsZv-otaSmwtHcpU-XkMZ9VeL3C9peMQiYDtlGhg
supabase.storage.bucket=mouse-images

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080
